# -*- coding: utf-8 -*-
"""Assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/Narmadhai-M/Narmadhai-M/blob/main/Assignment_1.ipynb
"""



s = "Hi there Sam!"
x=s.split()
print(x)

planet = "Earth"
diameter = 12742
print("The diameter of {} is {} kilometer.".format(planet,diameter))

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])

import numpy as np
array=np.zeros(10)
print(array)

import numpy as np
array=np.ones(10)*5
print(array)

import numpy as np
x=np.arange(20,36)
y=(x%2==0)
z=x[y]
print(z)

x=np.arange(0,9).reshape((3,3))
print(x)

a=np.array([1,2,3])
b=np.array([4,5,6])
x=np.concatenate((a,b))
print(x)

dataframe=np.random.randint(15,size=(3,2))
print(dataframe)

from pandas.core.window.rolling import timedelta
from pandas.io.sql import date
import pandas as pd
sdate = date(2023, 1, 1)
edate = date(2023, 2, 10)
pd.date_range(sdate,edate-timedelta(days=1),freq='d')

import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
dataframe=pd.DataFrame(lists)
print(dataframe)